server:
  port: 8071
eureka:
  instance:
    hostname: localhost
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
      # 测试时关闭自我保护机制，保证不可用服务及时踢出
  server:
    enable-self-preservation: false
    #清理无效服务间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 10000

#    enable-self-preservation: false