#server:
#  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liangle1986/mywuwu-config.git
          searchPaths: mywuwu-config
      label: master
      username: liangle1986@126.com
      password: le5201314